---
- hosts: routers
  gather_facts: no
  vars_files:
    - "secrets/vault.yml"

  tasks:
  - import_role:
      name: interfaces
  - name: save running to startup when modified
    ios_config:
      save_when: modified
