---
- name: set desired snmp settings
  hosts: routers
  gather_facts: no
  vars_files:
    - "secrets/vault.yml"

  vars:
    snmp_server:
      - snmp-server community network_as_code RO 99
      - snmp-server trap-source Loopback0
      - snmp-server contact fakrul@alam.rocks
      - snmp-server host 100.100.250.10 version 2c public udp-port 161

  tasks:
  - name: get the current snmp-server config
    ios_command:
      commands:
        - "show running-config full | include snmp-server"
    register: get_config

  - debug: var=get_config.stdout_lines

  - name: set snmp-server configs
    with_items: "{{ snmp_server }}"
    ios_config:
      lines:
        - "{{ item }}"
    register: set_snmp

  - name: remove snmp-server configs
    when: "(get_config.stdout_lines[0] != '') and (item not in snmp_server)"
    with_items: "{{ get_config.stdout_lines[0] }}"
    register: remove_snmp
    ios_config:
      lines:
        - "no {{ item }}"
