---
# tasks file for routing
#

- name: enable ipv6 routing
  ios_config:
    lines:
      - "ipv6 unicast-routing"

- name: ospfv3 process
  ios_config:
    lines:
      - "router ospfv3 100"

- name: ospfv3 process - router id
  ios_config:
    lines: 
      - "router-id {{ router_id }}"
    parents: router ospfv3 100

- name: ospfv3 interfaces
  ios_config:
    lines:
      - ipv6 ospf 100 area {{ item.ospfv3.area }}
    parents: interface {{ item.ios_if }}
  when: item.ospfv3 is defined
  loop: "{{ interfaces }}"

- name: ospfv3 interfaces - passive
  ios_config:
    lines:
      - passive-interface {{ item.ios_if }}
    parents: router ospfv3 100
  when: 
    - item.ospfv3 is defined
    - item.ospfv3.passive is defined
  loop: "{{ interfaces }}"

- name: removed ipv4 address family
  ios_config:
    lines:
      - "no address-family ipv4 unicast"
    parents: router ospfv3 100
