- name: configure acl for snmp
  cisco.ios.ios_acls:
    config:
    - afi: ipv4
      acls:
      - name: 99
        acl_type: standard
        aces:
        - grant: permit
          source:
            address: 100.100.250.100
        - grant: permit
          source:
            address: 100.100.250.200
    state: merged