---
# tasks file for roles/common

- name: include nameserver configuration
  include: nameserver.yml
- name: include ntp configuration
  include: ntp.yml
- name: include acl configuration 
  include: acl.yml
- name: include snmp configuration 
  include: snmp.yml  