---
# tasks file for ntp
#
- name: configure ntp server
  cisco.ios.ios_ntp:
    server: "{{ item }}"
    source_int: Loopback0
    logging: false
    state: present
  with_items: "{{ ntp_servers }}"