---
# tasks file for snmp
#
- name: get the current snmp-server config
  ios_command:
    commands:
      - "show running-config full | include snmp-server"
  register: get_config
- debug: var=get_config.stdout_lines

- name: remove snmp-server configs
  #when: "(get_config.stdout_lines != '') and (item not in snmp_server)"
  when: "(get_config.stdout_lines[0] != '') and (item not in snmp_server)"
  with_items: "{{ get_config.stdout_lines[0] }}"
  register: remove_snmp
  ios_config:
    lines:
      - "no {{ item }}"

- name: set snmp-server configs
  with_items: "{{ snmp_server }}"
  ios_config:
    lines:
      - "{{ item }}"
  register: set_snmp

