---
hostname: iosxe1
domain_name: alam.rocks
router_id: 100.100.100.1
rtr_role: core
name_servers:
  - 4.4.4.4
  - 1.1.1.1
  - 9.9.9.9

bgp:
  local_as: 65534
  neighbor:
    ipv4:
     - peer: 100.100.100.2
       remote_as: 65534
       ibgp: true
       update_source: Loopback0
       default_originate: true

    ipv6:
     - peer: "2001:db8:901:beef::2"
       remote_as: 65534
       ibgp: true
       update_source: Loopback0

interfaces:
  #- ios_if: "GigabitEthernet1"
    #desc: "management interface - do not change"
    #enabled: true
    #ipv4: dhcp
    #ipv6: fd5d:12c9:2201:1::1/64

  - ios_if: "GigabitEthernet2"
    desc: "iosxe1-iosxe2"
    enabled: true
    ipv4: "192.168.100.1/30"
    ipv6: "2001:db8:201::a/64"
    ospf:
      area: "0.0.0.0"
    ospfv3:
      area: "0.0.0.0"

  - ios_if: "GigabitEthernet3"
    desc: "free-interface"
    enabled: false
    ipv4: "192.168.250.1/30"

  - ios_if: "loopback0"
    desc: "Loopback"
    enabled: true
    ipv4: "100.100.100.1/32"
    ipv6: "2001:db8:901:beef::1/128"
    ospf:
      area: "0.0.0.0"
      passive: true
    ospfv3:
      area: "0.0.0.0"
      passive: true

